### ISSUE TITLE
Outdated libdeflate causes FTBFS with gcc 16

### ISSUE THREAD

**Issue by intelfx** [inikep/lzbench#284]
libdeflate 1.24 fails to compile using `gcc (GCC) 16.1.1 20260430` due to, ultimately, inability to parse evex512 (or its negation, no-evex512) in the target attribute causing the entire attribute to be ignored and, subsequently, AVX512 intrinsics to be rejected:

<details>
<summary>lz/libdeflate/lib/adler32.o build log</summary>

```console
$ make
<...>
cc -march=native -O2 -pipe -fno-plt -fexceptions -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fuse-ld=mold -flto=auto -fuse-linker-plugin   -Wno-unknown-pragmas -Wno-sign-compare -Wno-conversion -Wno-error=int-conversion -fomit-frame-pointer -fstrict-aliasing -ffast-math -O3 -DNDEBUG -Dunix -I. -DZXC_STATIC_DEFINE   -Ilz/libdeflate lz/libdeflate/lib/adler32.c -c -o lz/libdeflate/lib/adler32.o
In file included from lz/libdeflate/lib/adler32.c:28:
lz/libdeflate/lib/x86/adler32_template.h:135:12: error: attribute ‘target’ argument ‘no-evex512’ is unknown
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      |            ^~~~~~~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:102:33: note: in definition of macro ‘CONCAT_IMPL’
  102 | #define CONCAT_IMPL(a, b)       a##b
      |                                 ^
lz/libdeflate/lib/lib_common.h:104:33: note: in expansion of macro ‘CONCAT’
  104 | #define ADD_SUFFIX(name)        CONCAT(name, SUFFIX)
      |                                 ^~~~~~
lz/libdeflate/lib/x86/adler32_template.h:135:1: note: in expansion of macro ‘ADD_SUFFIX’
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      | ^~~~~~~~~~
In file included from lz/libdeflate/lib/adler32.c:128:
lz/libdeflate/lib/x86/adler32_impl.h:83:41: error: attribute ‘target’ argument ‘no-evex512’ is unknown
   83 | #  define adler32_x86_avx512_vl256_vnni adler32_x86_avx512_vl256_vnni
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:102:33: note: in expansion of macro ‘adler32_x86_avx512_vl256_vnni’
  102 | #define CONCAT_IMPL(a, b)       a##b
      |                                 ^
lz/libdeflate/lib/lib_common.h:103:33: note: in expansion of macro ‘CONCAT_IMPL’
  103 | #define CONCAT(a, b)            CONCAT_IMPL(a, b)
      |                                 ^~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:104:33: note: in expansion of macro ‘CONCAT’
  104 | #define ADD_SUFFIX(name)        CONCAT(name, SUFFIX)
      |                                 ^~~~~~
lz/libdeflate/lib/x86/adler32_template.h:183:1: note: in expansion of macro ‘ADD_SUFFIX’
  183 | ADD_SUFFIX(adler32_x86)(u32 adler, const u8 *p, size_t len)
      | ^~~~~~~~~~
lz/libdeflate/lib/x86/adler32_template.h:135:12: error: attribute ‘target’ argument ‘evex512’ is unknown
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      |            ^~~~~~~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:102:33: note: in definition of macro ‘CONCAT_IMPL’
  102 | #define CONCAT_IMPL(a, b)       a##b
      |                                 ^
lz/libdeflate/lib/lib_common.h:104:33: note: in expansion of macro ‘CONCAT’
  104 | #define ADD_SUFFIX(name)        CONCAT(name, SUFFIX)
      |                                 ^~~~~~
lz/libdeflate/lib/x86/adler32_template.h:135:1: note: in expansion of macro ‘ADD_SUFFIX’
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      | ^~~~~~~~~~
lz/libdeflate/lib/x86/adler32_impl.h:95:41: error: attribute ‘target’ argument ‘evex512’ is unknown
   95 | #  define adler32_x86_avx512_vl512_vnni adler32_x86_avx512_vl512_vnni
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:102:33: note: in expansion of macro ‘adler32_x86_avx512_vl512_vnni’
  102 | #define CONCAT_IMPL(a, b)       a##b
      |                                 ^
lz/libdeflate/lib/lib_common.h:103:33: note: in expansion of macro ‘CONCAT_IMPL’
  103 | #define CONCAT(a, b)            CONCAT_IMPL(a, b)
      |                                 ^~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:104:33: note: in expansion of macro ‘CONCAT’
  104 | #define ADD_SUFFIX(name)        CONCAT(name, SUFFIX)
      |                                 ^~~~~~
lz/libdeflate/lib/x86/adler32_template.h:183:1: note: in expansion of macro ‘ADD_SUFFIX’
  183 | ADD_SUFFIX(adler32_x86)(u32 adler, const u8 *p, size_t len)
      | ^~~~~~~~~~
In file included from lz/libdeflate/lib/x86/adler32_impl.h:101:
lz/libdeflate/lib/x86/adler32_template.h: In function ‘adler32_x86_avx512_vl512_vnni’:
lz/libdeflate/lib/x86/adler32_template.h:197:21: warning: AVX512F vector return without AVX512F enabled changes the ABI [-Wpsabi]
  197 |         const vec_t ones = VSET1_8(1);
      |                     ^~~~
lz/libdeflate/lib/x86/adler32_template.h: In function ‘reduce_to_32bits_avx512_vl512_vnni’:
lz/libdeflate/lib/x86/adler32_template.h:135:12: note: the ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      |            ^~~~~~~~~~~~~~~~
lz/libdeflate/lib/lib_common.h:102:33: note: in definition of macro ‘CONCAT_IMPL’
  102 | #define CONCAT_IMPL(a, b)       a##b
      |                                 ^
lz/libdeflate/lib/lib_common.h:104:33: note: in expansion of macro ‘CONCAT’
  104 | #define ADD_SUFFIX(name)        CONCAT(name, SUFFIX)
      |                                 ^~~~~~
lz/libdeflate/lib/x86/adler32_template.h:135:1: note: in expansion of macro ‘ADD_SUFFIX’
  135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
      | ^~~~~~~~~~
make: *** [Makefile:882: lz/libdeflate/lib/adler32.o] Error 1
```

</details>

This started first happening with Clang due to https://github.com/llvm/llvm-project/pull/157034 (`[X86][AVX10] Remove EVEX512 and AVX10-256 implementations`), and was papered over in 0cdab83 (``Fix `libdeflate` build with Clang 22 by omitting evex512 target tokens``). However, the problem is not limited to Clang.

Fixed in: https://github.com/ebiggers/libdeflate/commit/6bb493615b0ef35c98fc4aa4ec04f448788db6a5 (`lib/x86: drop any mention of evex512`)

Please update libdeflate to at least v1.25 (better yet, to https://github.com/ebiggers/libdeflate/commit/fd2b8bab7131e54850c6f939deae97b183f12ef8).

**Comment by tansy** [comment]
Are you sure v1.25 , at that time, solves it?
Because there are later [commits](https://github.com/ebiggers/libdeflate/commits/master/) like 'Bring back evex512 and no-evex512 for clang 18', then 'Revert "lib/x86: Bring back evex512 and no-evex512 for clang 18"', and 'Disable AVX512 code with clang 18'.

**Comment by tansy** [comment]
Check if [this](https://github.com/inikep/lzbench/pull/285) solves your problem.
You can do it [this way](https://github.com/inikep/lzbench/pull/270#issuecomment-4156572170).

**Comment by intelfx** [comment]
Yes, ec823b9 resolves FTBFS with the described configuration.

Regarding your previous comment, it would seem there was an ongoing mess in clang 18, but it's irrelevant for GCC 16 and later. The overall direction is that AVX10-256 does not exist anymore, thus `evex512` target attributes and relevant `-m*` flags are going away (first from Clang, now from GCC too).

**Comment by tansy** [comment]
So it (\#285) can be merged.
