### PR TITLE
Add ppmd based on LZMA SDK 22.01 (thanks to @pps83)

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by pps83** [comment]
sounds stupid to say `thanks to @myself`, I simply based entire PR on some other diff that added another codec

**Comment by tansy** [comment]
All those functions ( pmalloc(), pfree(), CharWriter, CharWriterFunc() ) should be moved to `lzbench_ppmd_compress()`. They are small enough to move to the function body. Compressors.cpp is not private yard, it's public space and you should not litter it.

**Comment by pps83** [comment]
@tansy sorry for late reply. PR updated.

**Comment by pps83** [comment]
FYI, when I tried to use latest LZMA SDK 23.01 (instead of 22.01) I got compilation errors because lzbench already contains older lzma sdk parts (specifically 7zTypes.h, Compiler.h, Precomp.h and others are conflicting). With 22.01 at least it compiles cleanly.

when lzma is updated to 23.01, libppmd should also be updated to 23.01 at the same time

**Comment by inikep** [comment]
I cherry picked your commit to solve the conflicts. lzbench 2.0 will add support for ppmd soon.

**Comment by pps83** [comment]
Perhaps, would be good to update to latest [7zip](https://github.com/ip7z/7zip)/lzma sdk: https://7-zip.org/sdk.html (it's 24.09 now)

**Comment by inikep** [comment]
I tried lzma 24.09 but it doesn't work with ppmd based on LZMA SDK 23.01.
So in the next lzbench version we will have:
- ppmd based on LZMA SDK 23.01 (thanks to @pps83)
- lzma 23.01

**Comment by pps83** [comment]
you need to take both lzma sdk 24.09 and ppmd from 7zip 24.09 (I updated my [libppmd fork with 24.09](https://github.com/pps83/libppmd), works for me)

**Comment by tansy** [comment]
You can make new PR with new libppmd, as you call it. And don't add [vs](https://github.com/pps83/libppmd/tree/master/vs) dir, it has nothing to do with library not with PR.
Also you should call it PPMdI as it's 'I' variant of PPMd. Even 7-zip has two of them - 'H' and 'I'.

Also, before you do, consider [this PR](https://github.com/pps83/libppmd/pull/1).

**Comment by pps83** [comment]
> Also you should call it PPMdI as it's 'I' variant of PPMd. Even 7-zip has two of them - 'H' and 'I'.

I initially forked it from somewhere else. Not sure about ppmd variants, when I looked into the diff, they were almost non-existent.  Basically, I wanted to try ppmd that's supported by zip format. This ppmd compresses extremely well (better and faster than zstd at highest rate), however, it's a symmetrical codec, meaning that decoding takes the same amount of cpu as encoding.

**Comment by inikep** [comment]
Ppmd8 based on this PR is done at https://github.com/inikep/lzbench/commit/dec2f9627a4428e0db771fd8726df00ecfcf4a1e

**Comment by pps83** [comment]
> Ppmd8 based on this PR is done at [dec2f96](https://github.com/inikep/lzbench/commit/dec2f9627a4428e0db771fd8726df00ecfcf4a1e)

FYI, I'll update libppmd to avoid issues with lzma sdk, so that lzbench wouldn't be stuck where both would have to be udpated at the same time to avoid compilation issues.

**Comment by pps83** [comment]
Yes, this way you don't even need libppmd now.
